### ISSUE TITLE
Strategy Authentication

### ISSUE THREAD

**Issue by zmoshansky** [hassox/guardian#11]
Could you elaborate on what your thoughts are around how the Strategies would work? 

I've tried to work it out, but the `{:ok, resource}` syntax seems to make it verbose while handling the response. An alternative would just have the user run the authenticator on their own and add the `Guardian.sign_in`, with the added bonus of being able to have a spot to easily `reject` the authentication (deactivated account, flood control, etc).
```
defmodule Guardian.Authenticator do
  use Behaviour

  @doc "Runs an authentication strategy and returns the resource if successful"
  defcallback authenticate(conn :: Plug.Conn.t, params :: term) :: { :ok, resource :: term } | { :error, String.t }
end
```
```
defmodule Guardian.Strategy do
  @spec execute(Plug.Conn.t, term, term) :: Plug.Conn.t | {:error, String.t}
  def execute(conn, params, authenticator) do
    case authenticator.authenticate(conn, params) do
      {:ok, resource} -> Guardian.sign_in(conn, resource)
      {:error, message} -> {:error, message}
    end
  end
end
```
```
def create(conn, params = %{}) do
  case Guardian.Strategy.execute(conn, params, AuithenticatorModule) do
    conn -> conn
      |> redirect(to: user_path(conn, :index))
    {:error, message} -> conn
      |> put_flash(:error, message)
      |> redirect(to: "/")
  end
end
```

**Comment by zmoshansky** [comment]
I've created [Aeacus](https://github.com/zmoshansky/aeacus) as a potential authentication strategy to use with Guardian. If there was some behaviour for authenticators to abide by, I'd be happy to implement it and have it be the first of the auth strategies.

**Comment by hassox** [comment]
Hey @zmoshansky. I'm not sure yet if strategies are a good fit for Phoenix/guardian. Strategies were always problematic in warden. Omniauth presented a different way to achieve a similar result that often felt cleaner. Strategies require a lot of generalization for what is essentially a pretty simple setup. At this stage, I'm thinking that a strategy would be essentially a plug. It would take a lot of care to make sure it was general enough and I think by that point, it's probably more concise and less confusing to just write a plug for your scenario.

Log story short, I don't think they belong yet. I could be convinced, but it feels like elixir/Phoenix is different enough from rack/ruby that I'm just not sure they're a good fit.

**Comment by zmoshansky** [comment]
@hassox Thanks for the background information, I brought it up as I was looking at the TODO's for guardian and noticed it on there. I have worked with Omniauth as well and it worked well to get 4+ auth solutions up quickly. Do you know of any elixir equivalent?

**Comment by hassox** [comment]
Not specifically an omniauth equivalent but there is https://github.com/scrogson/oauth2 for oauth2. I've been thinking about something like this too. Still letting it percolate.

**Comment by zmoshansky** [comment]
Good to know, thanks
