### ISSUE TITLE
Problems with Guardian.JWT Joken config Modules decode function (keys: :atoms!)

### ISSUE THREAD

**Issue by werbitzky** [hassox/guardian#13]
I had problems verifying tokens from the auth headers, I always got an `{:error, "argument error"}` in my assigns which happened during JSON decoding of the claims.
Weirdly enough the problem seemed only to appear if I hadn't created a token before.

After looking deeper, I discovered, that it is not the recommended way for the Poison decoder configuration to use atoms as keys, read here:
https://github.com/devinus/poison#parser

> Note that keys: :atoms! reuses existing atoms, i.e. if :name was not allocated before the call, you will encounter an argument error message.

> You can use the keys: :atoms variant to make sure all atoms are created as needed. However, unless you absolutely know what you're doing, do not do it. Atoms are not garbage-collected, see Erlang Efficiency Guide for more info:

> Atoms are not garbage-collected. Once an atom is created, it will never be removed. The emulator will terminate if the limit for the number of atoms (1048576 by default) is reached.

The Guardian.JWT module however uses atoms as keys:

```elixir
  @doc false
  def decode(binary), do: JSON.decode!(binary, keys: :atoms!)
```

As I understand, this creates weird problems, where you have to anticipate and instatiate all atoms that you might need for the to-be-decoded JSON text before trying to decode it. Apart from that you could run out of atoms.
I will also open a ticket for the Joken guys, as they have a similar example for a config module in their README.

**Comment by werbitzky** [comment]
I overlooked, that using atoms was probably intended because of the function that is executed on load:

```elixir
  @doc false
  def load_required_atoms do
    IO.puts("Loading required atoms #{inspect([:iat, :aud, :sub, :exp, :iss, :s_csrf])}")
    :ok
  end
```

if you decide to stick with atoms, I suggest adding `:pems` to the list as this caused my problem in the first place

**Comment by hassox** [comment]
Thank you. I do need to add :pems to that list, I overlooked that one. 

The reason I chose atoms! Is because joken currently requires atoms, but since they're not garbage collected I don't just want to instantiate any old input. 

As a work around when I'm adding custom claims, I put a list of expected claims into the guardian config to pre-load them.


    config :guardian, Guardian
         atoms: [:one, :two]

I agree that it's less than ideal, but without quite a few changes to joken (and maybe even key lists) it's atoms at the moment.

**Comment by werbitzky** [comment]
The creator of Joken is now attempting to change Joken to work without atoms:
https://github.com/bryanjos/joken/pull/43

Do you see any problem with this I'm maybe not aware of?

**Comment by hassox** [comment]
I'd love to use strings as keys with joken. Way less issues and craziness to worry about. Joken had a pretty major change recently so it could work out of the box with strings where I only have to change Guardian.

**Comment by bryanjos** [comment]
The latest version of Joken may work better with strings since more is placed on the user as far as validation, etc. If there are any other changes to Joken that could help or anywhere in Guardian where I may be able to help out with this, I'm happy to help out.

**Comment by hassox** [comment]
Thanks @bryanjos. I'm going to try and move over to string keys shortly since atom keys are problematic when accepting keys generated by others

**Comment by hassox** [comment]
I have just updated Guardian to 0.5.0 to use string keys rather than atom keys. 

Please note that claims are provided now using strings rather than atoms where you're using them.
