### ISSUE TITLE
Question/Feature Request:

### ISSUE THREAD

**Issue by erneestoc** [hassox/guardian#15]
Is there a way to keep session upon app restart? Or if not, is it possible to hook up redis or something to handle this?

**Comment by erneestoc** [comment]
Other use case would be using Phoenix, inside amazons elasticbeanstalk (docker), and multiple availability zones.

**Comment by hassox** [comment]
Hey @erneestoc I'm not quite sure what you're asking. Keeping a session for longer than a browser session is related to how the cookies are setup for the session. 

The tokens that Guardian generates should work just fine across app-restarts.

**Comment by erneestoc** [comment]
Hmm.. I might be doing something wrong..   Every time I close and open the app, the unauthenticated method gets called...

```elixir
plug Guardian.Plug.EnsureSession, on_failure: { Atena.SessionController, :unauthenticated }
```

my pipeline looks like this.. 
```elixir
  pipeline :authenticated do
    plug Guardian.Plug.VerifyAuthorization
    plug Guardian.Plug.EnsureSession, on_failure: { Atena.SessionController, :unauthenticated }
  end
```

and this to authenticate my users..

``` elixir
{:ok, token, _} = Guardian.mint(%{id: account.user.id}, :api)
```

**Comment by hassox** [comment]
ok so there's no phoenix session being involved here. How are you making your call?

Can you add a plug in-between the VerifyAuthorization and EnsureSession and dump the headers to see what's making it there?

**Comment by erneestoc** [comment]
I'm storing the token using iOS keychain, and sending the param as "Authorization", "$token"..    The app restart I'm talking about is the phoenix process...   if I type cntl+c, and quit the app, turn it on again, the following requests wont be authenticated...    and it executes the on_failure: of EnsureSession...

**Comment by misaelpc** [comment]
Hi, I'm experimenting the same issue, after restart the phoenix application, I Get the following error:
Loading required atoms [:iat, :aud, :sub, :exp, :iss, :pems]
    :erlang.binary_to_existing_atom("pem", :utf8)
    (poison) lib/poison/parser.ex:97: Poison.Parser.object_name/2
    (poison) lib/poison/parser.ex:82: Poison.Parser.object_pairs/3
    (poison) lib/poison/parser.ex:36: Poison.Parser.parse/2
    (poison) lib/poison/parser.ex:50: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
    lib/joken/token.ex:116: Joken.Token.get_data/2
    lib/joken/token.ex:71: Joken.Token.decode/3
Auth Token  => eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVc2VyOjEiLCJwZW0iOnt9LCJpc3MiOiJBdGVuYSIsImlhdCI6MTQzNzc5NTY5MSwiZXhwIjoxNDQwMzg3NjkxLCJhdWQiOiJhcGkifQ.f4FGRf4rcMo5Lm85f4rGBaMX95hmvWuXslp7F2a58z4

The token Generation it's made with the following serializer =>
 
def for_token(%{:id => id}), do: {:ok, "User:#{id}" }
"User:1"

**Comment by hassox** [comment]
oh. Sorry I misunderstood the problem. This is due to the current setup of using atoms as keys https://github.com/hassox/guardian/issues/13

To sort this please ensure to include a list of atoms in your config that your app uses in its claims. Guardian sets up a few for you  [:iat, :aud, :sub, :exp, :iss, :pems].

    config :guardian, Guardian,
               atoms: [:pem, :something_else]
               ....

In guardian Poison is currently setup to use existing atoms (:erlang.binary_to_existing_atom) so these must be declared prior to trying to verify a token. By declaring these atoms early in your config, they're available. 

There is an outstanding issue to transition to string keys rather than atom keys for claims.

**Comment by hassox** [comment]
This has been updated in 0.5.0. Guardian now uses string keys rather than atom keys.
