### ISSUE TITLE
Printing of "Loading required atoms [:iat, :aud, :sub, :exp, :iss, :pems]"

### ISSUE THREAD

**Issue by bbhoss** [hassox/guardian#19]
This is really intrusive into my sea of green dots while running my tests. Is this still necessary? If so, I am quite curious as to why this is required.

**Comment by hassox** [comment]
@bbhoss this was part of a joken thing which I'm now removing. Making it so that keys are strings not atoms. I will at the same time remove that print

**Comment by hassox** [comment]
This has been removed in Guardian 0.5.0
