### ISSUE TITLE
Renaming some things

### ISSUE THREAD

**Issue by hassox** [hassox/guardian#22]
Hi folks. 

There's a bit of confusion around the names of things in Guardian. I'm not surprised because I'm pretty terrible at naming things.

The things that have currently been discussed are:

### Guardian.mint

This function generates a JWT, and calls hooks that incorporate behaviour. Mint does not seem to be a common word for this (it fits! but just not common)

Suggestions so far:
    Guardian.encode_and_sign

### Guardian.verify

In order to be symmetrical with the replacement for mint, the following has been suggested
    Guardian.decode_and_verify

### EnsureSession
This is  just flat out poorly named. It implies that you need to be running a session (which is not true).

An alternative might be
    EnsureTokenValidity

### VerifyAuthorization

This module fetches a token from the Authorization header, but could be named better.

Open for suggestions.

**Comment by zmoshansky** [comment]
I would suggest `Guardian.sign` & `Guardian.verify` for the functions, as it's fairly common terminology as far as cryptography goes, and mirrors [Phoenix.Token](http://hexdocs.pm/phoenix/Phoenix.Token.html). `encode_and_sign` is a bit tedious, although it is incredibly descriptive; so a bit of a trade-off.

`EnsureSession` -> `EnsureAuthorized` or `EnsureAuthorization` 
`VerifyAuthorization` -> `VerifyHeader` (Aligns well with `VerifySession`)

My 0.02C, hope it helps.

**Comment by adamesque** [comment]
Super happy about these changes. Thanks!
