### ISSUE TITLE
Less dependencies, more fun

### ISSUE THREAD

**Issue by lexmag** [hassox/guardian#23]
[Current usage](https://github.com/hassox/guardian/blob/c65fd77dc81c1817a2a97bdc6dd5a9f531e0c14e/lib/guardian/utils.ex#L10) of Calendar dependency is a huge overkill, especially for compilation, releases.

It might be replaced with:
```elixir
{mgsec, sec, _usec} = :os.timestamp
mgsec * 1_000_000 + sec
```

**Comment by hassox** [comment]
That sounds great :)

If you can put a PR together it will get in faster, otherwise I'll add it to my list.

**Comment by lexmag** [comment]
There will be PR soon. :smile:
