### ISSUE TITLE
Use Plug.Exception protocols for on_failure

### ISSUE THREAD

**Issue by hassox** [hassox/guardian#35]
It would be nice if on_failure were optional and we could make use of Plug.Exception protocols for Guardian errors.

**Comment by bbhoss** [comment]
I think the better solution is maybe have your own failure protocol, then have the default implementation to reraise. That way, you can do more than just set the status code, but by default it just bubbles up to Plug.Exception.

**Comment by hassox** [comment]
@bbhoss can you elaborate a bit. I'm not sure what you're thinking of.
