### ISSUE TITLE
Guardian.Plug.EnsureAuthenticated on failure using wrong controller

### ISSUE THREAD

**Issue by oscarduignan** [hassox/guardian#37]
Hi there,

Quite new to elixir and phoenix so apologies if this isn't a bug but a mistake in my code, I had a look at the code and couldn't see what was wrong with it to be able contribute a fix or confirm if it is a bug in Guardian or I'm just doing something wrong.

Basically when I use

```
plug Guardian.Plug.EnsureAuthenticated, on_failure: { SessionController, :new }
```

In a controller and the on_failure triggers rather than send me to the :new action of the SessionController it seems like it's trying to send me to the :new action of the current controller. I've attached a screenshot of the error and the code the code I'm getting this error with is here: controller where EnsureAuthenticated is being called, https://github.com/oscarduignan/phoenix-time-tracker/blob/master/web/controllers/user_controller.ex#L7; and the action it's trying to use for on_failure, https://github.com/oscarduignan/phoenix-time-tracker/blob/master/web/controllers/session_controller.ex#L6-L8. 

![ensureauthenticationonfailure](https://cloud.githubusercontent.com/assets/100650/9655017/68caf3b0-5226-11e5-91b3-aaa1664e4465.png)

**Comment by hassox** [comment]
Hi @oscarduignan. I think this is because in the SessionController#new function, when you call render you'll need to supply it with the view.

    render conn, Session.View, 'new.html', stuff: 'and things'

Unfortunately by the time we get to the view the connection has already cached what view it's going to use by default so you'll need to be explicit.

HTH
Daniel

**Comment by oscarduignan** [comment]
Thank you Daniel that did it! Still getting my head around Phoenix so I'm very greatful for your help solving that and thank you for all the work you've put into Guardian, it's proving really useful :+1: hopefully I'll be able to contribute something back soon as I get to know it and Phoenix better

**Comment by hassox** [comment]
Great to hear :) I always love help with Guardian. Good luck with Phoenix.
