### ISSUE TITLE
Permissions aren't working

### ISSUE THREAD

**Issue by ryanswapp** [hassox/guardian#39]
I've been playing around with permissions and haven't been able to get them working... I've set them in my config file:
```
permissions: %{
    admin: [
      :users
    ]
  }
```
 and then am assigning them on sign in like this:
```
Guardian.Plug.sign_in(user, :token, perms: %{ admin: [:users]}) 
```
In my controller I am then using:
```
plug Guardian.Plug.EnsurePermissions, on_failure: { Blog.UserController, :unauthenticated }, admin: [:users]
```
The on_failure callback gets called every time I try to access the controller. In order to figure out what was going on I started playing around with the Guardian.Permissions API. When I call:
```
Guardian.Permissions.to_value([:users]) 
```
it returns 0. I assume there is something wrong as the docs say that an integer from 1-31 should be assigned. 

In addition, when I inspect the claims the "pem" key looks like this:
```
"pem" => %{"admin" => 0}
```

Any ideas as to what is going on?

**Comment by hassox** [comment]
Hi, You're adding your permissions to the 'admin' set, but when you're checking them you're seeing 0 because it's looking in the default set.

    Gaurdian.Permissions.to_value([:users], :admin)

How are you setting your permissions on token generation?

**Comment by ryanswapp** [comment]
Are you referring to the Serializer? I just have the default setup that is in the README. Do I need to add more to it in order to support permissions?

**Comment by hassox** [comment]
No not the serializer. The point where you generate your token. It's either:

    Guardian.Plug.sign_in

or

    Guardian.encode_and_sign

**Comment by hassox** [comment]
I think I may have found it. 

    iex(1)> Guardian.Permissions.to_value([:users], :admin) 
    1
    iex(2)> Guardian.Permissions.to_value([:users], "admin")  
    0  

This is likely a problem since the string keys came in. Will get a fix out asap
