### ISSUE TITLE
Discussion: Guardian.Plug namespace

### ISSUE THREAD

**Issue by scrogson** [hassox/guardian#4]
I could be totally wrong, but I'm a tiny bit on the fence with the semantics of the `Plug` namespace.

Since [Plug][0] is generally concerned with a "connection", should the `Guardian.Plug` namespace be `Guardian.Conn` instead?

I realize that the `Guardian.Plug` namespace indicates that these modules provide the `Plug` contract (behaviour), just wondering if it's necessary?

Thoughts?

[0]: https://github.com/elixir-lang/plug

**Comment by hassox** [comment]
I'm not sure what the done thing is in elixir yet so I'm totally open to suggestions. I wanted a way to differentiate between Plug and Channel. I have a branch on my local that has channel support which, unsurprisingly is namespaced under Guardian.Channel.

If you think Conn is more appropriate I'm down.

**Comment by scrogson** [comment]
Channel as in `Phoenix` channels?

**Comment by hassox** [comment]
Yes. I can push the in-progress stuff up to a branch if you want to take a look.

**Comment by hassox** [comment]
https://github.com/hassox/guardian/tree/add-channel-integration
