### ISSUE TITLE
Use `not`, `and`, `or` for strictly boolean checks

### ISSUE THREAD

**Issue by lexmag** [hassox/guardian#41]
It signals that we are working with booleans - not truthy and falsy values. It's also slightly faster.

**Comment by hassox** [comment]
Hey @lexmag do you have an example of where in the code you mean?

**Comment by lexmag** [comment]
Yes, there is an example https://github.com/hassox/guardian/blob/master/lib/guardian/plug.ex#L161.
And other `starts_with?/2 .. && ..` places in that module.

**Comment by doomspork** [comment]
@hassox if you haven't already started on this I'd be glad to give it a whirl.
