### ISSUE TITLE
Update to new version of joken

### ISSUE THREAD

**Issue by hassox** [hassox/guardian#46]
https://github.com/bryanjos/joken

**Comment by efries** [comment]
Hi,

Can you check if this is the right direction?
https://github.com/hassox/guardian/compare/master...efries:master

Beside 4 fails the tests are green. Validation is still missing.
```
1) test fails if the expiry has passed (GuardianTest)
     test/guardian_test.exs:58
2) test it is invalid if the aud is incorrect (GuardianTest)
     test/guardian_test.exs:65
3) test fails if the issuer is not correct (GuardianTest)
     test/guardian_test.exs:51
4) test verify! with a bad token (GuardianTest)
     test/guardian_test.exs:73
```
Please check careful. I'm new to Elixir. :-)

**Comment by hassox** [comment]
Hi @efries I decided to move away from Joken. Their API changes are too drastic considering that I'm only using it for encoding and decoding. I've put a PR together at https://github.com/hassox/guardian/pull/62 if you'd like to take a look :D
