### ISSUE TITLE
Guardian.Plug.sign_in is not injecting permissions

### ISSUE THREAD

**Issue by Pjino** [hassox/guardian#47]
I'm using and updated version of the Guardian example it seems that whatever combination of permissions I try to inject (for instance, "Guardian.Plug.sign_in(user, :token, perms: %{ default: :write_profile })" it won work.
When inspecting claims I always see: ..."pem" => %{"default" => -1},

**Comment by hassox** [comment]
Hi @Pjino. What version are you currently using? Can I see your config for guardian?

**Comment by Pjino** [comment]
Hi @hassox. I'm using the latest version of everything (Guardian, Phoenix,...) and I (think) I made all the necessary changes.
My config.exs looks like this:
![screen shot 2015-09-14 at 22 09 52](https://cloud.githubusercontent.com/assets/14219474/9861927/76b76db8-5b2d-11e5-9182-bce40813eff5.png)
and my controller is:
![screen shot 2015-09-14 at 22 11 53](https://cloud.githubusercontent.com/assets/14219474/9861986/c54fa468-5b2d-11e5-8bad-0d5114f27145.png)

**Comment by hassox** [comment]
Thanks. Just an FYI you have two hooks declared. 

The reason you're seeing the -1 is because you're setting the default permissions to Guardian.Permissions.max in sign in. If you had this instead do you still see -1?

    Guardian.Plug.sign_in(user, :token, perms: %{ default: [:write_profile] })

**Comment by Pjino** [comment]
I changed it to:
Guardian.Plug.sign_in(user, :token, perms: %{ default: [:write_profile] })
![screen shot 2015-09-15 at 09 52 26](https://cloud.githubusercontent.com/assets/14219474/9872195/8c110982-5b8f-11e5-9166-5e593c33d9b2.png)
and:
Guardian.Plug.sign_in(user, :token, perms: %{ default: [:read_profile, :write_profile] })
![screen shot 2015-09-15 at 08 51 24](https://cloud.githubusercontent.com/assets/14219474/9872200/92c2b5dc-5b8f-11e5-822b-fb1326f3e073.png)
And it still's the same. I even created new users for each case but nothing changed.
![screen shot 2015-09-15 at 08 39 55](https://cloud.githubusercontent.com/assets/14219474/9872206/a0b64762-5b8f-11e5-846d-14ce77a2b85e.png)
![screen shot 2015-09-15 at 08 52 54](https://cloud.githubusercontent.com/assets/14219474/9872207/a2b72040-5b8f-11e5-8a22-15afdbe4cdea.png)
My hooks are:
![screen shot 2015-09-15 at 08 55 26](https://cloud.githubusercontent.com/assets/14219474/9872144/49c60546-5b8f-11e5-9c4b-18c5f8c60cdc.png)

**Comment by yuyabee** [comment]
I think I'm seeing the same issue. 
In IEx, ```Guardian.Permissions.to_value [:read_profile, :write_profile], :default``` returns 0, and ```Guardian.Permissions.availble``` returns [] where it's supposed to return list of permissions.
I have exact the same configuration as the example.
@Pjino please try these functions and see if we are talking about the same problem.

**Comment by Pjino** [comment]
@yuyabee Yes, `Guardian.Permissions.to_value [:read_profile, :write_profile], :default` returns `0` and `Guardian.Permissions.availble` returns an error: `UndefinedFunctionError`

**Comment by yuyabee** [comment]
@Pjino Sorry, that was a typo, it's ```Guardian.Permissions.available```

**Comment by Pjino** [comment]
@yuyabee Yes, it returns []. Sorry for testing it in such a rush that I didn't even try to see why it returned undefined...It was obvious:)

**Comment by hassox** [comment]
I haven't been able to repeat this locally :( I'm guessing that you're running Guardian 0.6.1 which was a bit buggy. GuardianDb _was_ requiring this version. I've updated GuardianDb to rely on 0.6.2 in v 0.1.2. Can you please update guardian db and guardian and see if you still have the same issue?

**Comment by yuyabee** [comment]
@hassox Yes that was it. Upgrading to 0.6.2 solved it. Thank you so much.

**Comment by hassox** [comment]
Phew! Thanks so much for looking into it :)
