### ISSUE TITLE
What's the best way to get and use a user JWT using API approach?

### ISSUE THREAD

**Issue by DeodorantMan** [hassox/guardian#49]
I followed the guardian phoenix example, and I'm a little confused on how to get a token for a user so they can start making API requests.

I tried copying and pasting the token I got from the browser session, into a API requests Authorization header, but it's failing on EnsureAuthenticated matching on { :error, :no_session }.

This might sound dumb, but..
Will I need to create a user session before calling an API endpoint?

I would like to do something like `POST: http://example.com/api/v1/login` and pass in an email and password. Then it would return a JWT to use for future API requests.

Anyway, I would like to see your approach on this, because I feel like the example app didnt go into much detail about making API requests with a JWT.

Thank you for any help.

**Comment by hassox** [comment]
He @DeodorantMan 

You don't need to create a phoenix session to use it. The first step is to create the token:

    Guardian.encode_and_sign(user, :api)

This will give you the token, then in your pipeline somewhere use the Guardian.Plug.VerifyHeader plug. This will check for a present token. You can also use the Guardian.Plug.LoadResource plug after that to fetch your user.

Can you provide code for you router and controller?

**Comment by DeodorantMan** [comment]
My router looks like this.
```
defmodule App.Router do
  use App.Web, :router
  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
  end

  scope "/api/v1", App.Api.V1 do
    post "/auth", AuthController, :create
    pipe_through [:api]
    resources "/users", UserController
    resources "/cities", CityController
    resources "/countries", CountryController
  end
end
```

then my auth controller looks like this (not checking password yet for simplicity):
```
defmodule App.Api.V1.AuthController do
  use App.Web, :controller

  alias App.User
  alias App.UserQuery

  def create(conn, params = %{}) do
    user = Repo.one(UserQuery.by_email(params["user"]["email"] || ""))
    { :ok, jwt, _ } = Guardian.encode_and_sign(user, :api)
    json(conn, %{ jwt: jwt })
  end

  def unauthenticated_api(conn, _params) do
    the_conn = put_status(conn, 401)
    case Guardian.Plug.claims(conn) do
      { :error, reason } -> json(the_conn, %{ error: reason })
      _ -> json(the_conn, %{ error: "Login required" })
    end
  end

end
```

And then my city controller looks like this (the resource that I'm trying to authenticate):
```
defmodule App.Api.V1.CityController do
  use App.Web, :controller

  alias App.City
  alias App.Api.V1.AuthController

  plug Guardian.Plug.EnsureAuthenticated, on_failure: { AuthController, :unauthenticated_api }

  def index(conn, _params) do
    cities = Repo.preload(Repo.all(City), :country)
    render(conn, "index.json", cities: cities)
  end
end
```

What seems to be happening is the EnsureAuthenticated in my city controller is looking for a session. because the error I'm getting from the on_failure is `{"error":"no_session"}`.
When I comment that line out, it responds with the resource as It should.

Ok cool, so that's fine, at least I'm getting something back. But when I don't pass in a token in the header it still goes though and loads the resource. What?

That shouldn't happen, right? because in my router I have `plug Guardian.Plug.VerifyHeader, realm: "Bearer"`, and it should look for a token, No?

I must be doing something wrong, and I can't figure it out. It's been bugging me for a week now and I really like this library.

Any help would be great thanks.

**Comment by DeodorantMan** [comment]
I figured out my problem.
In my request header I was putting `Authorization: MYTOKEN`, when I needed to put `Authorization: Bearer MYTOKEN`
I found it after looking through the verify_header_test file.

Thank you for your help, and great work on the library.

**Comment by hassox** [comment]
Hi,

How are you putting the header in on your client? It should be

    Authorization: Bearer <jwt>

**Comment by hassox** [comment]
Great! Glad it worked out for you :)

**Comment by alduro** [comment]
@ddcech can you please share your Guardian config part in config.ex ? I'm getting the same issue. Thanks !

**Comment by ddcech** [comment]
@alduro I don't have that specific project anymore (it was 1 year ago), but I was using this example [phoenix_guardian](https://github.com/hassox/phoenix_guardian/tree/ueberauth-guardian) project.

**Comment by aislanmaia** [comment]
Hey guys, I'm authenticating in my client and trying to logout putting the Authorization: Bearer ${`localStorage.token`} but the server is returning:  

(KeyError) key :plug_session not found in: %{Api.Router => {[], %{}}, :guardian_default_claims => {:ok, %{"aud" => "User:1", .... etc } 

Any ideas ?? Thanks in advance.

**Comment by aislanmaia** [comment]
Forgive me, I've achieved my goal just following what Daniel Neighman suggested in your [blog post.](http://hassox.github.io/elixir/guardian/2015/06/30/api-authentication-with-guardian.html) on the last post comment.
