### ISSUE TITLE
How can I authenticate a user to bypass Guardian.Plug.EnsureAuthenticated in controller's test?

### ISSUE THREAD

**Issue by viniciusmkm** [hassox/guardian#53]
Hi!

I am using guardian to authenticate users to access private actions in my phoenix application and everything is working fine.

The problem is that I can't make my controllers tests to pass. All requests are falling on the plug  Guardian.Plug.EnsureAuthenticated, rendering the login page instead of executing the action normally.

I have already tried the following in my controller test:

```elixir
  setup do
    user = Repo.insert(%User{})
    conn = conn()
            |> sign_conn()
            |> Guardian.Plug.sign_in(user, :token, perms: %{ default: Guardian.Permissions.max })
    {:ok, conn: conn}
  end
```

The `sign_conn` I got from [plug's tests](https://github.com/elixir-lang/plug/blob/2181abb0e30b774f7640add3e5a5401567a87aca/test/plug/session/cookie_test.exs#L31-L35) and it is defined in my `ConnCase` exactly like it is in the link. 

I did that because just calling the `Guardian.Plug.sign_in` in the `conn()` was raising errors related to `fetch_session`

So, am I on the right path? If not, what is the best way to bypass this authentication on controller tests?

My best

**Comment by doomspork** [comment]
@viniciusmkm this is what did the trick for me:

```elixir
conn = conn()
       |> sign_conn
       |> Guardian.Plug.sign_in(resource, :token, perms: %{default: Guardian.Permissions.max})
       |> Guardian.Plug.VerifySession.call([])
```

There is a sample Phoenix + Guardian app [here](https://github.com/hassox/phoenix_guardian).  I recently took a stab at updating the dependencies and submitted a PR, you can check out those changes [here](https://github.com/hassox/phoenix_guardian/pull/5).

**Comment by viniciusmkm** [comment]
Hey @doomspork, thanks for the fast reply!

Adding the `VerirfySession` plug is raising the following error:

```
 ** (CaseClauseError) no case clause matching: {:error, "argument error"}
     stacktrace:
       lib/guardian/plug/verify_session.ex:28: Guardian.Plug.VerifySession.call/2
       (blog) web/router.ex:12: Blog.Router.browser_session/2
       (blog) web/router.ex:2: Blog.Router.match/4
       (blog) web/router.ex:1: Blog.Router.do_call/2
       (blog) lib/blog/endpoint.ex:1: Blog.Endpoint.phoenix_pipeline/1
       (blog) lib/phoenix/endpoint/render_errors.ex:34: Blog.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:193: Phoenix.ConnTest.dispatch/5
```

I changed the `sign_in` function to match the one you sent me:

```elixir
      @default_opts [
        store: :cookie,
        key: "foobar",
        encryption_salt: "encrypted cookie salt",
        signing_salt: "signing salt"
      ]
      @secret String.duplicate("abcdef0123456789", 8)
      @signing_opts Plug.Session.init(Keyword.put(@default_opts, :encrypt, false))

      def conn_with_fetched_session(the_conn) do
        put_in(the_conn.secret_key_base, @secret)
        |> Plug.Session.call(@signing_opts)
        |> Plug.Conn.fetch_session
      end

      def sign_in(conn, resource, perms \\ Guardian.Permissions.max) do
        conn
        |> conn_with_fetched_session
        |> Guardian.Plug.sign_in(resource, :token, perms: %{default: perms})
        |> Guardian.Plug.VerifySession.call([])
      end
```

And the guardian and phoenix versions in mix.lock are:

```elixir
%{"comeonin": {:hex, :comeonin, "1.1.4"},
  "cowboy": {:hex, :cowboy, "1.0.3"},
  "cowlib": {:hex, :cowlib, "1.0.1"},
  "decimal": {:hex, :decimal, "1.1.0"},
  "ecto": {:hex, :ecto, "1.0.2"},
  "fs": {:hex, :fs, "0.9.2"},
  "guardian": {:hex, :guardian, "0.6.2"},
  "joken": {:hex, :joken, "0.15.0"},
  "phoenix": {:hex, :phoenix, "1.0.3"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "1.2.0"},
  "phoenix_html": {:hex, :phoenix_html, "2.2.0"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.0.0"},
  "plug": {:hex, :plug, "1.0.2"},
  "poison": {:hex, :poison, "1.5.0"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.9.1"},
  "ranch": {:hex, :ranch, "1.1.0"},
  "uuid": {:hex, :uuid, "1.0.1"}}
```

Any ideia about this?

**Comment by doomspork** [comment]
The error suggests `Guardian.Plug.sign_in(resource, :token, perms: %{default: perms})` is failing ([plug.ex#L83](https://github.com/hassox/guardian/blob/master/lib/guardian/plug.ex#L83)) but I'm not entirely sure why.  Have you double checked your setup and configuration are correct?

**Comment by viniciusmkm** [comment]
Well, they are exactly as I pasted above :confused:

**Comment by doomspork** [comment]
@viniciusmkm there should be some configuration in `config/config.exs` like your permissions and serializer.  Without seeing more of the code it's hard for me to discern the cause, perhaps someone else will have more insight.

**Comment by viniciusmkm** [comment]
@doomspork, I have found the problem!

At my test setup I was doing:

```elixir
user = Repo.insert(%Blog.User{})
```

Just changed to:

```elixir
user = Repo.insert!(%Blog.User{})
```

And now it works!

Thanks for your help!
