### ISSUE TITLE
Logout method for API

### ISSUE THREAD

**Issue by vernomcrp** [hassox/guardian#56]
I login to api via Guardian.encode_and_sign(xxx). I cannot use Guardian.Plug.sign_out(conn) to logout from api. It said "cannot fetch_session". and method Guardian.revoke! do nothing with authentication data in header

**Comment by hassox** [comment]
Hi @vernomcrp. When you're logging out of a session it depends on if you're using something like GuardianDb to keep track of tokens you have out in the wild.

If you're not using GuardianDb or something similar, then on your client just forget the token. If you have a token and it checks out then it is valid. If you want something more robust, that's what GuardianDb was developed for.

When using GuardianDb, to logout a session you should use the Guardian.revoke! function which will cause the token to be deleted from the db. This will make that token invalid in the future if someone tries to use it again.
