### ISSUE TITLE
IO.puts

### ISSUE THREAD

**Issue by joelfperion** [hassox/guardian#72]
I think it's a code smell for a library to do 'IO.puts' on errors, the errors should be reflected only in the function's output.

My opinion only so if you agree I could make the fix myself and submit a PR.

**Comment by hassox** [comment]
@joelfperion I agree. I'd love some other way to pas up the error. Perhaps a call to a logger or just pass it back?

**Comment by joelfperion** [comment]
It seems to me that most libraries in elixir don't log (httpoison, phoenix, dynamo, etc..) so maybe to conform to their best practice just pass it back?

**Comment by hassox** [comment]
sounds good. Merged the PR
