### ISSUE TITLE
Pre-configure 'keys' so that the atoms are generated only once.

### ISSUE THREAD

**Issue by hassox** [hassox/guardian#8]
On startup, pre-generate all allowable keys so that they're only generated once rather than going string -> atom -> string in Guardian.Keys

**Comment by jhosteny** [comment]
As you pointed out, the keys will be pre-configured, and small in number. So, an easy solution would be to call `String.to_existing_atom`, and if the exception is thrown, create it with the call to `String.to_atom`. The exception should be thrown only once for each of this small number of keys.

**Comment by jhosteny** [comment]
FYI:

```elixir
iex(5)> fn -> for n <- 1..1_000_000, do: String.to_atom "foo" end |> :timer.tc |> elem(0) |> Kernel./(1_000_000)
2.727668
iex(6)> fn -> for n <- 1..1_000_000, do: String.to_existing_atom "foo" end |> :timer.tc |> elem(0) |> Kernel./(1_000_000)
2.912363
```

**Comment by hassox** [comment]
Not sure that I understand the difference between `String.to_existing_atom` + on failure `String.to_atom` and just calling `String.to_atom` in the first place.

**Comment by jhosteny** [comment]
My original understanding was that even if the input binary was the same, calling `String.to_atom` would generate a new atom in the global atom array in the VM, whose entries are not GC'ed. But I now believe that this is incorrect. So, this should be safe to close. Sorry for the noise!
